import type { FileSystemTree } from "@webcontainer/api";

export const viteReactTemplate: FileSystemTree = {
  "package.json": {
    file: {
      contents: JSON.stringify(
        {
          scripts: {
            dev: "vite --host 0.0.0.0 --clearScreen false",
          },
          dependencies: {
            "@vitejs/plugin-react": "4.3.1",
            vite: "5.4.0",
            typescript: "5.5.3",
            react: "18.3.1",
            "react-dom": "18.3.1",
          },
          devDependencies: {},
        },
        null,
        2,
      ),
    },
  },
  "index.html": {
    file: {
      contents: [
        "<!doctype html>",
        '<html lang="zh-Hant">',
        "  <head>",
        '    <meta charset="UTF-8" />',
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
        "    <title>WebContainer MVP</title>",
        "  </head>",
        "  <body>",
        '    <div id="root">',
        '      <main class="shell">',
        '        <section class="card">',
        '          <p class="eyebrow">Loading React</p>',
        "          <h1>WebContainer preview is loading...</h1>",
        "          <p>If this text stays visible, the React entry has not rendered successfully yet.</p>",
        "        </section>",
        "      </main>",
        "    </div>",
        "    <script>",
        "      window.addEventListener('error', (event) => {",
        "        document.body.innerHTML = `",
        '          <main class="shell">',
        '            <section class="card error-card">',
        '              <p class="eyebrow">Window error</p>',
        "              <h1>Preview runtime error</h1>",
        "              <pre>${event.message}\\n${event.filename}:${event.lineno}:${event.colno}</pre>",
        "            </section>",
        "          </main>",
        "        `;",
        "      });",
        "",
        "      window.addEventListener('unhandledrejection', (event) => {",
        "        document.body.innerHTML = `",
        '          <main class="shell">',
        '            <section class="card error-card">',
        '              <p class="eyebrow">Unhandled rejection</p>',
        "              <h1>Preview async error</h1>",
        "              <pre>${event.reason?.stack || event.reason}</pre>",
        "            </section>",
        "          </main>",
        "        `;",
        "      });",
        "",
        "      window.setTimeout(() => {",
        "        const root = document.getElementById('root');",
        "        if (root && !(root.textContent || '').trim()) {",
        "          root.innerHTML = `",
        '            <main class="shell">',
        '              <section class="card error-card">',
        '                <p class="eyebrow">Empty React root</p>',
        "                <h1>React mounted but rendered no visible content</h1>",
        "                <p>Vite is running and CSS loaded, but #root became empty after React took over.</p>",
        "              </section>",
        "            </main>",
        "          `;",
        "        }",
        "      }, 1200);",
        "    </script>",
        '    <script type="module" src="/src/main.tsx"></script>',
        "  </body>",
        "</html>",
      ].join("\n"),
    },
  },
  "vite.config.ts": {
    file: {
      contents: [
        'import { defineConfig } from "vite";',
        'import react from "@vitejs/plugin-react";',
        "",
        "export default defineConfig({",
        "  plugins: [react()],",
        "});",
      ].join("\n"),
    },
  },
  src: {
    directory: {
      "main.tsx": {
        file: {
          contents: [
            'import React from "react";',
            'import { createRoot } from "react-dom/client";',
            'import "./style.css";',
            'import App from "./App";',
            "",
            'const root = document.getElementById("root");',
            "",
            "function showRenderError(error: unknown) {",
            "  const message = error instanceof Error ? error.stack ?? error.message : String(error);",
            "  document.body.innerHTML = `",
            '    <main class="shell">',
            '      <section class="card error-card">',
            '        <p class="eyebrow">React render error</p>',
            "        <h1>Preview failed to render</h1>",
            "        <pre>${message}</pre>",
            "      </section>",
            "    </main>",
            "  `;",
            "}",
            "",
            "try {",
            "  if (!root) {",
            '    throw new Error("Root element #root was not found");',
            "  }",
            "",
            "  console.info('Rendering WebContainer MVP React app');",
            "",
            "  createRoot(root).render(",
            "    <App />,",
            "  );",
            "} catch (error) {",
            "  showRenderError(error);",
            "}",
          ].join("\n"),
        },
      },
      "App.tsx": {
        file: {
          contents: [
            'import React from "react";',
            "",
            "export default function App() {",
            "  return (",
            '    <main className="shell">',
            '      <section className="card">',
            '        <p className="eyebrow">WebContainer MVP</p>',
            "        <h1>Hello from Vite + React</h1>",
            "        <p>If you can see this text, the WebContainer dev server started successfully.</p>",
            "      </section>",
            "    </main>",
            "  );",
            "}",
          ].join("\n"),
        },
      },
      "style.css": {
        file: {
          contents: [
            "body {",
            "  margin: 0;",
            "  font-family: Inter, system-ui, sans-serif;",
            "  background: #0f172a;",
            "  color: white;",
            "}",
            "",
            ".shell {",
            "  min-height: 100vh;",
            "  display: flex;",
            "  align-items: center;",
            "  justify-content: center;",
            "  padding: 2rem;",
            "  text-align: center;",
            "}",
            "",
            ".card {",
            "  max-width: 640px;",
            "  border: 1px solid rgba(125, 211, 252, 0.35);",
            "  border-radius: 24px;",
            "  background: rgba(15, 23, 42, 0.72);",
            "  box-shadow: 0 24px 80px rgba(56, 189, 248, 0.18);",
            "  padding: 3rem;",
            "}",
            "",
            "h1 {",
            "  margin: 0.75rem 0;",
            "  font-size: clamp(2rem, 6vw, 4rem);",
            "}",
            "",
            "p {",
            "  font-size: 1.125rem;",
            "}",
            "",
            "pre {",
            "  max-width: 100%;",
            "  overflow: auto;",
            "  white-space: pre-wrap;",
            "  word-break: break-word;",
            "  text-align: left;",
            "}",
            "",
            ".error-card {",
            "  border-color: rgba(248, 113, 113, 0.55);",
            "}",
            "",
            ".eyebrow {",
            "  color: #38bdf8;",
            "  letter-spacing: 0.16em;",
            "  text-transform: uppercase;",
            "}",
          ].join("\n"),
        },
      },
    },
  },
};
